# Generated by Django 2.2.5 on 2019-09-05 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190905_1935'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='account.ClientProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='account.DriverProfile'),
            preserve_default=False,
        ),
    ]
