# Generated by Django 2.2.5 on 2019-09-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20190905_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('driver_accepted', 'Accepted by driver'), ('driver_arrived', 'Driver arrived'), ('client_in_car', 'Client is in car'), ('completed', 'Order is completed')], max_length=255, null=True),
        ),
    ]
